using System;
using System.Collections.Generic;
using System.Text;

namespace Navicon.JsonSerializer.Models.Enums
{
    public enum Gender
    {
        Agender,
        Androgyne,
        Androgynous,
        Bigender,
        Cis,
        Cisgender,
        CisFemale,
        CisMale,
        CisMan,
        CisWoman,
        CisgenderFemale,
        CisgenderMale,
        CisgenderMan,
        CisgenderWoman,
        FemaletoMale,
        FTM,
        GenderFluid,
        GenderNonconforming,
        GenderQuestioning,
        GenderVariant,
        Genderqueer,
        Intersex,
        MaletoFemale,
        MTF,
        Neither,
        Neutrois,
        NonBinary,
        Other,
        Pangender,
        Trans,
        TransFemale,
        TransMale,
        TransMan,
        TransPerson,
        TransWoman,
        Transfeminine,
        Transgender,
        TransgenderFemale,
        TransgenderMale,
        TransgenderMan,
        TransgenderPerson,
        TransgenderWoman,
        Transmasculine,
        Transsexual,
        TranssexualFemale,
        TranssexualMale,
        TranssexualMan,
        TranssexualPerson,
        TranssexualWoman,
        TwoSpirit,
    }
}
